version: '3.10'

services:
  flask:
    image: docker/dev-environments
    command: python /flask/app.py
    build: .
    volumes:
      - ./flask:/vsCodeServerVolumeteste-musing_yonath
    environment:
       TZ: America/Fortaleza
    restart: always
    ports:
      - "4005:80"
