version: '3.10'

services:
  flask:
    image: flask:dev-enviromments
    command: python/flask/app.py
    build: 
    volumes:
      - ./flask:/flask
    environment:
       TZ: America/Fortaleza
    restart: always
    ports:
      - "4005:80"
